<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-96T1B1J" ignored="0" name="logintest" tests="2" failures="1" timestamp="2021-05-06T23:49:28 IST" time="51.259" errors="0">
  <testcase name="login" time="16.937" classname="tests.logintest">
    <failure type="java.lang.AssertionError" message="expected [successful] but found [failure]">
      <![CDATA[java.lang.AssertionError: expected [successful] but found [failure]
at tests.logintest.login(logintest.java:56)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- login -->
  <testcase name="login" time="16.907" classname="tests.logintest"/>
</testsuite> <!-- logintest -->
